### ISSUE TITLE
Develop lessons learned presentation and deliver to State Officers

### ISSUE THREAD

**Issue by jbcannon313** [CMSgov/CMCS-DSG-DSS-Oversight#171] opened 2020-10-20 16:15 UTC
The lessons learned presentation will go over lessons learned from MECT/MEET as well as lessons learned from the pilots. This will help with the transition to a more streamlined cert process and eventually OBC. CMS will decide how to present, e.g., place presentation on wiki, use lunch and learn, leverage color team meetings

@pkroft pull previous lessons learned presentation material
@jbcannon313 and Sandy develop new deck from previous material
@LizLeBreton @sjschaffzin40 decide on timing and where/how to present material

**Comment by NAretakis** [comment] 2020-10-22 20:29
Closing this issue because it is a duplicate of #157. If we need to adjust/edit #157 please edit #157 accordingly.

**Closed by NAretakis** 2020-10-22 20:29 UTC
Labels: Comms/Engagement
